name: Build APK Kivy

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Descargar el código
        uses: actions/checkout@v3

      - name: Configurar Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias del sistema operativo (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Configurar entorno y dependencias compatibles
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade buildozer cython
          pip install --upgrade "pythonforandroid>=2024.0"
          pip install openpyxl requests pillow pyjnius certifi urllib3 idna charset-normalizer

      - name: Compilar la APK con Buildozer
        run: buildozer android debug

      - name: Guardar la APK generada
        uses: actions/upload-artifact@v4
        with:
          name: CampoData-APK
          path: bin/*.apk
